// <auto-generated />
using System;
using CafeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeManagement.Models.Entities.Bangluong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("KhauTru")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Luong")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Nam")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<decimal?>("PhuCap")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("SoGio")
                        .HasColumnType("integer");

                    b.Property<int>("Thang")
                        .HasColumnType("integer");

                    b.Property<decimal>("TongLuong")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdNV", "Nam", "Thang")
                        .IsUnique();

                    b.ToTable("Bangluong", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Chamcong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("interval");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdNV", "Ngay")
                        .IsUnique();

                    b.ToTable("Chamcong", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Dinhluong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DonVi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IdSP")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdThanhPhan")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<Guid?>("NhanvienId")
                        .HasColumnType("uuid");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdThanhPhan");

                    b.HasIndex("NhanvienId");

                    b.HasIndex("IdSP", "IdThanhPhan")
                        .IsUnique();

                    b.ToTable("Dinhluong", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Dongnhap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IdPhieuNhap")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSP")
                        .HasColumnType("uuid");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdPhieuNhap");

                    b.HasIndex("IdSP");

                    b.ToTable("Dongnhap", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Hoadon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("GiamGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("IdKH")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uuid");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayLapHD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("TongCong")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdKH");

                    b.HasIndex("IdNV");

                    b.HasIndex("MaHD")
                        .IsUnique();

                    b.ToTable("Hoadon", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.HoadonCT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IdHD")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSP")
                        .HasColumnType("uuid");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdHD");

                    b.HasIndex("IdSP");

                    b.ToTable("HoadonCT", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Khachhang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CongNo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Khachhang", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Nhacungcap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CongNo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<string>("NguoiDaiDien")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Nhacungcap", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Nhanvien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CMND")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Luong")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("NgayThaiPhuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Nhanvien", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.NhomSP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("integer");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("NhomSP", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Phieuchi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IdNCC")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdNV")
                        .HasColumnType("uuid");

                    b.Property<int>("LoaiChiPhi")
                        .HasColumnType("integer");

                    b.Property<string>("MaPC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayLapPC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int>("PhuongThucThanhToan")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdNCC");

                    b.HasIndex("IdNV");

                    b.HasIndex("MaPC")
                        .IsUnique();

                    b.ToTable("Phieuchi", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Phieunhap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("IdNCC")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uuid");

                    b.Property<string>("MaPN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayLapPN")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdNCC");

                    b.HasIndex("IdNV");

                    b.HasIndex("MaPN")
                        .IsUnique();

                    b.ToTable("Phieunhap", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Sanpham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("IdNhom")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int>("SLTonMin")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdNhom");

                    b.ToTable("Sanpham", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Tieuhao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DonGiaVon")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("IdHoadonCT")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSP")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdHoadonCT");

                    b.HasIndex("IdSP");

                    b.ToTable("Tieuhao", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Bangluong", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Bangluongs")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Chamcong", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Chamcongs")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Dinhluong", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Sanpham", "Sanpham")
                        .WithMany("Dinhluongs")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Sanpham", "ThanhphanSanpham")
                        .WithMany("DinhluongThanhPhans")
                        .HasForeignKey("IdThanhPhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Nhanvien", null)
                        .WithMany("Dinhluongs")
                        .HasForeignKey("NhanvienId");

                    b.Navigation("Sanpham");

                    b.Navigation("ThanhphanSanpham");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Dongnhap", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Phieunhap", "Phieunhap")
                        .WithMany("Dongnhaps")
                        .HasForeignKey("IdPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Sanpham", "Sanpham")
                        .WithMany("Dongnhaps")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phieunhap");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Hoadon", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Khachhang", "Khachhang")
                        .WithMany("Hoadons")
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Hoadons")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.HoadonCT", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Hoadon", "Hoadon")
                        .WithMany("HoadonCTs")
                        .HasForeignKey("IdHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Sanpham", "Sanpham")
                        .WithMany("HoadonCTs")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hoadon");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Phieuchi", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Nhacungcap", "Nhacungcap")
                        .WithMany()
                        .HasForeignKey("IdNCC");

                    b.HasOne("CafeManagement.Models.Entities.Nhanvien", "Nhanvien")
                        .WithMany()
                        .HasForeignKey("IdNV");

                    b.Navigation("Nhacungcap");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Phieunhap", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.Nhacungcap", "Nhacungcap")
                        .WithMany("Phieunhaps")
                        .HasForeignKey("IdNCC")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Nhanvien", "Nhanvien")
                        .WithMany("Phieunhaps")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nhacungcap");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Sanpham", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.NhomSP", "NhomSP")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdNhom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhomSP");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Tieuhao", b =>
                {
                    b.HasOne("CafeManagement.Models.Entities.HoadonCT", "HoadonCT")
                        .WithMany("Tieuhaos")
                        .HasForeignKey("IdHoadonCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeManagement.Models.Entities.Sanpham", "Sanpham")
                        .WithMany("Tieuhaos")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoadonCT");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Hoadon", b =>
                {
                    b.Navigation("HoadonCTs");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.HoadonCT", b =>
                {
                    b.Navigation("Tieuhaos");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Nhacungcap", b =>
                {
                    b.Navigation("Phieunhaps");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Nhanvien", b =>
                {
                    b.Navigation("Bangluongs");

                    b.Navigation("Chamcongs");

                    b.Navigation("Dinhluongs");

                    b.Navigation("Hoadons");

                    b.Navigation("Phieunhaps");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.NhomSP", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Phieunhap", b =>
                {
                    b.Navigation("Dongnhaps");
                });

            modelBuilder.Entity("CafeManagement.Models.Entities.Sanpham", b =>
                {
                    b.Navigation("DinhluongThanhPhans");

                    b.Navigation("Dinhluongs");

                    b.Navigation("Dongnhaps");

                    b.Navigation("HoadonCTs");

                    b.Navigation("Tieuhaos");
                });
#pragma warning restore 612, 618
        }
    }
}
