-- Paste this script into Supabase SQL Editor and run.
-- This script is idempotent: running multiple times will not duplicate seeded rows.
-- 
-- Default accounts created:
-- 1. Admin (admin@cafemanagement.local / Admin@123)
-- 2. Kế toán (keytoan@cafemanagement.local / Keytoan@123)
-- 3. Thu ngân (thunga@cafemanagement.local / Thunga@123)
-- 
-- Change passwords immediately after first deployment for security.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Bootstrap ASP.NET Core Identity tables.
CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" uuid PRIMARY KEY,
    "Name" varchar(256),
    "NormalizedName" varchar(256),
    "ConcurrencyStamp" text
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" uuid PRIMARY KEY,
    "DisplayName" text,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp NOT NULL,
    "UpdatedAt" timestamp NOT NULL,
    "UserName" varchar(256),
    "NormalizedUserName" varchar(256),
    "Email" varchar(256),
    "NormalizedEmail" varchar(256),
    "EmailConfirmed" boolean NOT NULL DEFAULT false,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL DEFAULT false,
    "AccessFailedCount" integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId" uuid NOT NULL REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE,
    "ClaimType" text,
    "ClaimValue" text
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
    "ClaimType" text,
    "ClaimValue" text
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" varchar(128) NOT NULL,
    "ProviderKey" varchar(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
    "RoleId" uuid NOT NULL REFERENCES "AspNetRoles"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" uuid NOT NULL REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
    "LoginProvider" varchar(128) NOT NULL,
    "Name" varchar(128) NOT NULL,
    "Value" text,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles"("NormalizedName");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers"("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers"("NormalizedEmail");
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims"("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims"("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins"("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles"("RoleId");

-- Bootstrap core tables if database is empty.
CREATE TABLE IF NOT EXISTS "NhomSP" (
    "Id" uuid PRIMARY KEY,
    "TenNhom" varchar(100) NOT NULL,
    "MoTa" varchar(500),
    "PhanLoai" integer NOT NULL,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Sanpham" (
    "Id" uuid PRIMARY KEY,
    "IdNhom" uuid NOT NULL REFERENCES "NhomSP"("Id") ON DELETE RESTRICT,
    "TenSP" varchar(100) NOT NULL,
    "MoTa" varchar(500),
    "GiaBan" numeric(10,2) NOT NULL,
    "GiaNhap" numeric(10,2) NOT NULL,
    "SoLuongTon" integer NOT NULL DEFAULT 0,
    "SLTonMin" integer NOT NULL DEFAULT 0,
    "DonViTinh" varchar(50),
    "IsActive" boolean NOT NULL DEFAULT true,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Khachhang" (
    "Id" uuid PRIMARY KEY,
    "TenKH" varchar(100) NOT NULL,
    "Sdt" varchar(20),
    "Email" varchar(100),
    "DiaChi" varchar(200),
    "CongNo" numeric(10,2) DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Nhanvien" (
    "Id" uuid PRIMARY KEY,
    "TenNV" varchar(100) NOT NULL,
    "Sdt" varchar(20),
    "Email" varchar(100),
    "DiaChi" varchar(200),
    "CMND" varchar(20),
    "NgaySinh" timestamp,
    "ChucVu" varchar(50),
    "Luong" numeric(10,2),
    "TrangThai" integer NOT NULL DEFAULT 1,
    "NgayVaoLam" timestamp NOT NULL,
    "NgayThaiPhuc" timestamp,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Hoadon" (
    "Id" uuid PRIMARY KEY,
    "MaHD" varchar(50) NOT NULL UNIQUE,
    "IdKH" uuid NOT NULL REFERENCES "Khachhang"("Id") ON DELETE RESTRICT,
    "IdNV" uuid NOT NULL REFERENCES "Nhanvien"("Id") ON DELETE RESTRICT,
    "NgayLapHD" timestamp NOT NULL,
    "ThanhTien" numeric(12,2) NOT NULL,
    "GiamGia" numeric(12,2),
    "TongCong" numeric(12,2) NOT NULL,
    "PhuongThucThanhToan" integer NOT NULL DEFAULT 1,
    "TrangThai" integer NOT NULL DEFAULT 0,
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "HoadonCT" (
    "Id" uuid PRIMARY KEY,
    "IdHD" uuid NOT NULL REFERENCES "Hoadon"("Id") ON DELETE CASCADE,
    "IdSP" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE RESTRICT,
    "SoLuong" integer NOT NULL,
    "DonGia" numeric(10,2) NOT NULL,
    "ThanhTien" numeric(12,2) NOT NULL,
    "GhiChu" varchar(200)
);

CREATE TABLE IF NOT EXISTS "Dinhluong" (
    "Id" uuid PRIMARY KEY,
    "IdSP" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE CASCADE,
    "IdThanhPhan" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE CASCADE,
    "SoLuong" integer NOT NULL,
    "DonVi" varchar(50),
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_Sanpham_IdNhom" ON "Sanpham"("IdNhom");
CREATE INDEX IF NOT EXISTS "IX_Dinhluong_IdSP" ON "Dinhluong"("IdSP");
CREATE INDEX IF NOT EXISTS "IX_Dinhluong_IdThanhPhan" ON "Dinhluong"("IdThanhPhan");
CREATE INDEX IF NOT EXISTS "IX_Hoadon_IdKH" ON "Hoadon"("IdKH");
CREATE INDEX IF NOT EXISTS "IX_Hoadon_IdNV" ON "Hoadon"("IdNV");
CREATE INDEX IF NOT EXISTS "IX_HoadonCT_IdHD" ON "HoadonCT"("IdHD");
CREATE INDEX IF NOT EXISTS "IX_HoadonCT_IdSP" ON "HoadonCT"("IdSP");

DO $$
DECLARE
    v_now timestamp := now();

    v_role_admin uuid;
    v_role_ketoan uuid;
    v_role_thungan uuid;

    v_user_admin uuid;
    v_user_ketoan uuid;
    v_user_thungan uuid;

    v_nhom_cafe uuid;
    v_nhom_trasua uuid;
    v_nhom_banh uuid;
    v_nhom_nguyenlieu uuid;

    v_sp_cafeden uuid;
    v_sp_bacxiu uuid;
    v_sp_trasua uuid;
    v_sp_tiramisu uuid;
    v_sp_cafebot uuid;
    v_sp_suadac uuid;
    v_sp_cafesua uuid;

    v_kh uuid;
    v_nv uuid;
    v_hd uuid;
BEGIN
    -- Identity roles used by the application.
    SELECT "Id" INTO v_role_admin FROM "AspNetRoles" WHERE "Name" = 'Admin' LIMIT 1;
    IF v_role_admin IS NULL THEN
        v_role_admin := gen_random_uuid();
        INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
        VALUES (v_role_admin, 'Admin', 'ADMIN', gen_random_uuid()::text);
    END IF;

    SELECT "Id" INTO v_role_ketoan FROM "AspNetRoles" WHERE "Name" = 'Kế toán' LIMIT 1;
    IF v_role_ketoan IS NULL THEN
        v_role_ketoan := gen_random_uuid();
        INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
        VALUES (v_role_ketoan, 'Kế toán', 'KẾ TOÁN', gen_random_uuid()::text);
    END IF;

    SELECT "Id" INTO v_role_thungan FROM "AspNetRoles" WHERE "Name" = 'Thu ngân' LIMIT 1;
    IF v_role_thungan IS NULL THEN
        v_role_thungan := gen_random_uuid();
        INSERT INTO "AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp")
        VALUES (v_role_thungan, 'Thu ngân', 'THU NGÂN', gen_random_uuid()::text);
    END IF;

    -- Identity users - create default accounts for each role (PROD & DEV)
    -- Admin user (admin@cafemanagement.local)
    SELECT "Id" INTO v_user_admin FROM "AspNetUsers" WHERE "UserName" = 'admin@cafemanagement.local' LIMIT 1;
    IF v_user_admin IS NULL THEN
        v_user_admin := gen_random_uuid();
        INSERT INTO "AspNetUsers"
        ("Id", "DisplayName", "IsActive", "CreatedAt", "UpdatedAt", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash")
        VALUES
        (v_user_admin, 'System Admin', true, v_now, v_now, 'admin@cafemanagement.local', 'ADMIN@CAFEMANAGEMENT.LOCAL', 'admin@cafemanagement.local', 'ADMIN@CAFEMANAGEMENT.LOCAL', true, 'AQAAAAIAAYagAAAAEP83Iigfh4QEAByrtrARZ8urSbftiPb/qWvt2dp4s+QDfLUjYQiXidSTAunOgUeSRw==');
        INSERT INTO "AspNetUserRoles" ("UserId", "RoleId") VALUES (v_user_admin, v_role_admin);
    END IF;

    -- Kế toán user (keytoan@cafemanagement.local)
    SELECT "Id" INTO v_user_ketoan FROM "AspNetUsers" WHERE "UserName" = 'keytoan@cafemanagement.local' LIMIT 1;
    IF v_user_ketoan IS NULL THEN
        v_user_ketoan := gen_random_uuid();
        INSERT INTO "AspNetUsers"
        ("Id", "DisplayName", "IsActive", "CreatedAt", "UpdatedAt", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash")
        VALUES
        (v_user_ketoan, 'Kế Toán', true, v_now, v_now, 'keytoan@cafemanagement.local', 'KEYTOAN@CAFEMANAGEMENT.LOCAL', 'keytoan@cafemanagement.local', 'KEYTOAN@CAFEMANAGEMENT.LOCAL', true, 'AQAAAAIAAYagAAAAEO23LKoJRydBt8QxO2/ZOKv93ngM0OnqOAkx4qdvNJ1jsByp70a57RZv7+VSwrwoJQ==');
        INSERT INTO "AspNetUserRoles" ("UserId", "RoleId") VALUES (v_user_ketoan, v_role_ketoan);
    END IF;

    -- Thu ngân user (thunga@cafemanagement.local)
    SELECT "Id" INTO v_user_thungan FROM "AspNetUsers" WHERE "UserName" = 'thunga@cafemanagement.local' LIMIT 1;
    IF v_user_thungan IS NULL THEN
        v_user_thungan := gen_random_uuid();
        INSERT INTO "AspNetUsers"
        ("Id", "DisplayName", "IsActive", "CreatedAt", "UpdatedAt", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash")
        VALUES
        (v_user_thungan, 'Thu Ngân', true, v_now, v_now, 'thunga@cafemanagement.local', 'THUNGA@CAFEMANAGEMENT.LOCAL', 'thunga@cafemanagement.local', 'THUNGA@CAFEMANAGEMENT.LOCAL', true, 'AQAAAAIAAYagAAAAEGxjTGEMyd1Tnhs/VPs6JNlKCVGkzvGw/L7HhP76tB8sgdk7tEitoDyE6ekc6+lq7g==');
        INSERT INTO "AspNetUserRoles" ("UserId", "RoleId") VALUES (v_user_thungan, v_role_thungan);
    END IF;


    -- Categories (PhanLoai: DoUong=1, ThucAn=2, PhuLieu=4)
    SELECT "Id" INTO v_nhom_cafe FROM "NhomSP" WHERE "TenNhom" = 'Ca phe' LIMIT 1;
    IF v_nhom_cafe IS NULL THEN
        v_nhom_cafe := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_cafe, 'Ca phe', 'Nhom ca phe nong/lanh', 1, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhom_trasua FROM "NhomSP" WHERE "TenNhom" = 'Tra sua' LIMIT 1;
    IF v_nhom_trasua IS NULL THEN
        v_nhom_trasua := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_trasua, 'Tra sua', 'Nhom do uong tra sua', 1, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhom_banh FROM "NhomSP" WHERE "TenNhom" = 'Banh ngot' LIMIT 1;
    IF v_nhom_banh IS NULL THEN
        v_nhom_banh := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_banh, 'Banh ngot', 'Nhom banh/an nhe', 2, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhom_nguyenlieu FROM "NhomSP" WHERE "TenNhom" = 'Nguyen lieu' LIMIT 1;
    IF v_nhom_nguyenlieu IS NULL THEN
        v_nhom_nguyenlieu := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_nguyenlieu, 'Nguyen lieu', 'Nhom nguyen lieu pha che', 4, v_now, v_now);
    END IF;

    -- Products
    SELECT "Id" INTO v_sp_cafeden FROM "Sanpham" WHERE "TenSP" = 'Ca phe den' LIMIT 1;
    IF v_sp_cafeden IS NULL THEN
        v_sp_cafeden := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_cafeden, v_nhom_cafe, 'Ca phe den', 'Ca phe den da', 30000, 12000, 120, 20, 'ly', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_bacxiu FROM "Sanpham" WHERE "TenSP" = 'Bac xiu' LIMIT 1;
    IF v_sp_bacxiu IS NULL THEN
        v_sp_bacxiu := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_bacxiu, v_nhom_cafe, 'Bac xiu', 'Bac xiu da', 35000, 15000, 100, 20, 'ly', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_trasua FROM "Sanpham" WHERE "TenSP" = 'Tra sua tran chau' LIMIT 1;
    IF v_sp_trasua IS NULL THEN
        v_sp_trasua := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_trasua, v_nhom_trasua, 'Tra sua tran chau', 'Tra sua truyen thong', 40000, 18000, 90, 15, 'ly', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_tiramisu FROM "Sanpham" WHERE "TenSP" = 'Tiramisu' LIMIT 1;
    IF v_sp_tiramisu IS NULL THEN
        v_sp_tiramisu := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_tiramisu, v_nhom_banh, 'Tiramisu', 'Banh tiramisu mieng', 45000, 22000, 50, 10, 'mieng', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_cafebot FROM "Sanpham" WHERE "TenSP" = 'Cafe bot' LIMIT 1;
    IF v_sp_cafebot IS NULL THEN
        v_sp_cafebot := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_cafebot, v_nhom_nguyenlieu, 'Cafe bot', 'Nguyen lieu pha cafe', 0, 350, 10000, 1000, 'g', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_suadac FROM "Sanpham" WHERE "TenSP" = 'Sua dac' LIMIT 1;
    IF v_sp_suadac IS NULL THEN
        v_sp_suadac := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_suadac, v_nhom_nguyenlieu, 'Sua dac', 'Nguyen lieu sua dac', 0, 200, 8000, 800, 'ml', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_cafesua FROM "Sanpham" WHERE "TenSP" = 'Cafe sua' LIMIT 1;
    IF v_sp_cafesua IS NULL THEN
        v_sp_cafesua := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_sp_cafesua, v_nhom_cafe, 'Cafe sua', 'Cafe sua da', 38000, 16000, 9999, 0, 'ly', true, v_now, v_now);
    END IF;

    -- Recipe rows
    IF NOT EXISTS (SELECT 1 FROM "Dinhluong" WHERE "IdSP" = v_sp_cafesua AND "IdThanhPhan" = v_sp_cafebot) THEN
        INSERT INTO "Dinhluong"
        ("Id", "IdSP", "IdThanhPhan", "SoLuong", "DonVi", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES
        (gen_random_uuid(), v_sp_cafesua, v_sp_cafebot, 20, 'g', '1 ly cafe sua dung 20g cafe', v_now, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Dinhluong" WHERE "IdSP" = v_sp_cafesua AND "IdThanhPhan" = v_sp_suadac) THEN
        INSERT INTO "Dinhluong"
        ("Id", "IdSP", "IdThanhPhan", "SoLuong", "DonVi", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES
        (gen_random_uuid(), v_sp_cafesua, v_sp_suadac, 30, 'ml', '1 ly cafe sua dung 30ml sua', v_now, v_now);
    END IF;

    -- One customer and one employee for dashboards
    SELECT "Id" INTO v_kh FROM "Khachhang" WHERE "TenKH" = 'Khach le' LIMIT 1;
    IF v_kh IS NULL THEN
        v_kh := gen_random_uuid();
        INSERT INTO "Khachhang"
        ("Id", "TenKH", "Sdt", "Email", "DiaChi", "CongNo", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES
        (v_kh, 'Khach le', NULL, NULL, NULL, 0, true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nv FROM "Nhanvien" WHERE "TenNV" = 'Nhan vien mac dinh' LIMIT 1;
    IF v_nv IS NULL THEN
        v_nv := gen_random_uuid();
        INSERT INTO "Nhanvien"
        ("Id", "TenNV", "Sdt", "Email", "DiaChi", "CMND", "NgaySinh", "ChucVu", "Luong", "TrangThai", "NgayVaoLam", "NgayThaiPhuc", "NgayTao", "NgayCapNhat")
        VALUES
        (v_nv, 'Nhan vien mac dinh', NULL, NULL, NULL, NULL, NULL, 'Thu ngan', 9000000, 1, v_now, NULL, v_now, v_now);
    END IF;

    -- One invoice and one invoice detail sample
    SELECT "Id" INTO v_hd FROM "Hoadon" WHERE "MaHD" = 'HD-SEED-0001' LIMIT 1;
    IF v_hd IS NULL THEN
        v_hd := gen_random_uuid();
        INSERT INTO "Hoadon"
        ("Id", "MaHD", "IdKH", "IdNV", "NgayLapHD", "ThanhTien", "GiamGia", "TongCong", "PhuongThucThanhToan", "TrangThai", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES
        (v_hd, 'HD-SEED-0001', v_kh, v_nv, v_now, 30000, 0, 30000, 1, 2, 'Hoa don seed mau', v_now, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "HoadonCT" WHERE "IdHD" = v_hd AND "IdSP" = v_sp_cafeden) THEN
        INSERT INTO "HoadonCT"
        ("Id", "IdHD", "IdSP", "SoLuong", "DonGia", "ThanhTien", "GhiChu")
        VALUES
        (gen_random_uuid(), v_hd, v_sp_cafeden, 1, 30000, 30000, 'Dong seed mau');
    END IF;

    RAISE NOTICE 'Seed completed successfully.';
END $$;

COMMIT;
