-- Supabase bootstrap script for CafeManagement
-- Run this in Supabase SQL Editor after clearing the schema.
--
-- What this script creates:
-- - simple Users table for plain-text login
-- - product/category/customer/employee/invoice tables
-- - seed data for 3 demo users and sample business data
--
-- Login demo accounts:
-- - admin@cafemanagement.local / Admin@123
-- - keytoan@cafemanagement.local / Admin@123
-- - thunga@cafemanagement.local / Admin@123

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- --------------------------------------------------
-- Authentication
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" varchar(100) NOT NULL,
    "Password" text NOT NULL,
    "Role" varchar(50) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedDate" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users"("Email");

-- --------------------------------------------------
-- Core business tables
-- --------------------------------------------------
CREATE TABLE IF NOT EXISTS "Product" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(200) NOT NULL,
    "Description" varchar(500),
    "Price" numeric(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS "NhomSP" (
    "Id" uuid PRIMARY KEY,
    "TenNhom" varchar(100) NOT NULL,
    "MoTa" varchar(500),
    "PhanLoai" integer NOT NULL,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Sanpham" (
    "Id" uuid PRIMARY KEY,
    "IdNhom" uuid NOT NULL REFERENCES "NhomSP"("Id") ON DELETE RESTRICT,
    "TenSP" varchar(100) NOT NULL,
    "MoTa" varchar(500),
    "GiaBan" numeric(10,2) NOT NULL,
    "GiaNhap" numeric(10,2) NOT NULL,
    "SoLuongTon" integer NOT NULL DEFAULT 0,
    "SLTonMin" integer NOT NULL DEFAULT 0,
    "DonViTinh" varchar(50),
    "IsActive" boolean NOT NULL DEFAULT true,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Khachhang" (
    "Id" uuid PRIMARY KEY,
    "TenKH" varchar(100) NOT NULL,
    "Sdt" varchar(20),
    "Email" varchar(100),
    "DiaChi" varchar(200),
    "CongNo" numeric(10,2) DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Nhanvien" (
    "Id" uuid PRIMARY KEY,
    "TenNV" varchar(100) NOT NULL,
    "Sdt" varchar(20),
    "Email" varchar(100),
    "DiaChi" varchar(200),
    "CMND" varchar(20),
    "NgaySinh" timestamp,
    "ChucVu" varchar(50),
    "Luong" numeric(10,2),
    "TrangThai" integer NOT NULL DEFAULT 1,
    "NgayVaoLam" timestamp NOT NULL,
    "NgayThaiPhuc" timestamp,
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Hoadon" (
    "Id" uuid PRIMARY KEY,
    "MaHD" varchar(50) NOT NULL UNIQUE,
    "IdKH" uuid NOT NULL REFERENCES "Khachhang"("Id") ON DELETE RESTRICT,
    "IdNV" uuid NOT NULL REFERENCES "Nhanvien"("Id") ON DELETE RESTRICT,
    "NgayLapHD" timestamp NOT NULL,
    "ThanhTien" numeric(12,2) NOT NULL,
    "GiamGia" numeric(12,2),
    "TongCong" numeric(12,2) NOT NULL,
    "PhuongThucThanhToan" integer NOT NULL DEFAULT 1,
    "TrangThai" integer NOT NULL DEFAULT 0,
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "HoadonCT" (
    "Id" uuid PRIMARY KEY,
    "IdHD" uuid NOT NULL REFERENCES "Hoadon"("Id") ON DELETE CASCADE,
    "IdSP" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE RESTRICT,
    "SoLuong" integer NOT NULL,
    "DonGia" numeric(10,2) NOT NULL,
    "ThanhTien" numeric(12,2) NOT NULL,
    "GhiChu" varchar(200)
);

CREATE TABLE IF NOT EXISTS "Phieunhap" (
    "Id" uuid PRIMARY KEY,
    "MaPN" varchar(50) NOT NULL UNIQUE,
    "IdNCC" uuid NOT NULL,
    "IdNV" uuid NOT NULL,
    "NgayLapPN" timestamp NOT NULL,
    "TongTien" numeric(12,2) NOT NULL,
    "TrangThai" integer NOT NULL DEFAULT 0,
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Dongnhap" (
    "Id" uuid PRIMARY KEY,
    "IdSP" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE RESTRICT,
    "IdPhieuNhap" uuid NOT NULL REFERENCES "Phieunhap"("Id") ON DELETE CASCADE,
    "SoLuong" integer NOT NULL,
    "DonGia" numeric(10,2) NOT NULL,
    "GhiChu" varchar(200)
);

CREATE TABLE IF NOT EXISTS "Phieuchi" (
    "Id" uuid PRIMARY KEY,
    "MaPC" varchar(50) NOT NULL UNIQUE,
    "IdNV" uuid,
    "IdNCC" uuid,
    "NgayLapPC" timestamp NOT NULL,
    "SoTien" numeric(12,2) NOT NULL,
    "PhuongThucThanhToan" integer NOT NULL DEFAULT 1,
    "LoaiChiPhi" integer NOT NULL DEFAULT 0,
    "TrangThai" integer NOT NULL DEFAULT 0,
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Dinhluong" (
    "Id" uuid PRIMARY KEY,
    "IdSP" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE CASCADE,
    "IdThanhPhan" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE CASCADE,
    "SoLuong" integer NOT NULL,
    "DonVi" varchar(50),
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Tieuhao" (
    "Id" uuid PRIMARY KEY,
    "IdSP" uuid NOT NULL REFERENCES "Sanpham"("Id") ON DELETE RESTRICT,
    "IdHoadonCT" uuid NOT NULL REFERENCES "HoadonCT"("Id") ON DELETE CASCADE,
    "SoLuong" integer NOT NULL,
    "DonGiaVon" numeric(10,2) NOT NULL,
    "NgayTao" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Chamcong" (
    "Id" uuid PRIMARY KEY,
    "IdNV" uuid NOT NULL REFERENCES "Nhanvien"("Id") ON DELETE CASCADE,
    "Ngay" timestamp NOT NULL,
    "GioVao" interval,
    "GioRa" interval,
    "TrangThai" integer NOT NULL DEFAULT 0,
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "Bangluong" (
    "Id" uuid PRIMARY KEY,
    "IdNV" uuid NOT NULL REFERENCES "Nhanvien"("Id") ON DELETE CASCADE,
    "Nam" integer NOT NULL,
    "Thang" integer NOT NULL,
    "SoGio" integer NOT NULL,
    "Luong" numeric(12,2) NOT NULL,
    "PhuCap" numeric(12,2) DEFAULT 0,
    "KhauTru" numeric(12,2) DEFAULT 0,
    "TongLuong" numeric(12,2) NOT NULL,
    "TrangThai" integer NOT NULL DEFAULT 0,
    "GhiChu" varchar(200),
    "NgayTao" timestamp NOT NULL,
    "NgayCapNhat" timestamp NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_Sanpham_IdNhom" ON "Sanpham"("IdNhom");
CREATE INDEX IF NOT EXISTS "IX_Hoadon_IdKH" ON "Hoadon"("IdKH");
CREATE INDEX IF NOT EXISTS "IX_Hoadon_IdNV" ON "Hoadon"("IdNV");
CREATE INDEX IF NOT EXISTS "IX_HoadonCT_IdHD" ON "HoadonCT"("IdHD");
CREATE INDEX IF NOT EXISTS "IX_HoadonCT_IdSP" ON "HoadonCT"("IdSP");
CREATE INDEX IF NOT EXISTS "IX_Phunhap_IdNV" ON "Phieunhap"("IdNV");
CREATE INDEX IF NOT EXISTS "IX_Phunhap_IdNCC" ON "Phieunhap"("IdNCC");
CREATE INDEX IF NOT EXISTS "IX_Dongnhap_IdSP" ON "Dongnhap"("IdSP");
CREATE INDEX IF NOT EXISTS "IX_Dongnhap_IdPhieuNhap" ON "Dongnhap"("IdPhieuNhap");
CREATE INDEX IF NOT EXISTS "IX_Phieuchi_IdNV" ON "Phieuchi"("IdNV");
CREATE INDEX IF NOT EXISTS "IX_Phieuchi_IdNCC" ON "Phieuchi"("IdNCC");
CREATE INDEX IF NOT EXISTS "IX_Dinhluong_IdSP" ON "Dinhluong"("IdSP");
CREATE INDEX IF NOT EXISTS "IX_Dinhluong_IdThanhPhan" ON "Dinhluong"("IdThanhPhan");
CREATE INDEX IF NOT EXISTS "IX_Chamcong_IdNV" ON "Chamcong"("IdNV");
CREATE INDEX IF NOT EXISTS "IX_Bangluong_IdNV" ON "Bangluong"("IdNV");

DO $$
DECLARE
    v_now timestamp := now();
    v_nhom_cafe uuid;
    v_nhom_trasua uuid;
    v_nhom_banh uuid;
    v_nhom_nguyenlieu uuid;
    v_sp_cafeden uuid;
    v_sp_bacxiu uuid;
    v_sp_trasua uuid;
    v_sp_tiramisu uuid;
    v_sp_cafebot uuid;
    v_sp_suadac uuid;
    v_sp_cafesua uuid;
    v_khachle uuid;
    v_nhanvien uuid;
    v_hoadon uuid;
    v_hoadonct uuid;
BEGIN
    -- Users for simple login
    INSERT INTO "Users" ("Email", "Password", "Role", "IsActive", "CreatedDate")
    VALUES
        ('admin@cafemanagement.local', 'Admin@123', 'Admin', true, v_now),
        ('keytoan@cafemanagement.local', 'Admin@123', 'Kế toán', true, v_now),
        ('thunga@cafemanagement.local', 'Admin@123', 'Thu ngân', true, v_now)
    ON CONFLICT ("Email") DO UPDATE
    SET
        "Password" = EXCLUDED."Password",
        "Role" = EXCLUDED."Role",
        "IsActive" = EXCLUDED."IsActive";

    -- Categories
    SELECT "Id" INTO v_nhom_cafe FROM "NhomSP" WHERE "TenNhom" = 'Ca phe' LIMIT 1;
    IF v_nhom_cafe IS NULL THEN
        v_nhom_cafe := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_cafe, 'Ca phe', 'Nhom ca phe nong/lanh', 1, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhom_trasua FROM "NhomSP" WHERE "TenNhom" = 'Tra sua' LIMIT 1;
    IF v_nhom_trasua IS NULL THEN
        v_nhom_trasua := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_trasua, 'Tra sua', 'Nhom do uong tra sua', 1, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhom_banh FROM "NhomSP" WHERE "TenNhom" = 'Banh ngot' LIMIT 1;
    IF v_nhom_banh IS NULL THEN
        v_nhom_banh := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_banh, 'Banh ngot', 'Nhom banh/an nhe', 2, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhom_nguyenlieu FROM "NhomSP" WHERE "TenNhom" = 'Nguyen lieu' LIMIT 1;
    IF v_nhom_nguyenlieu IS NULL THEN
        v_nhom_nguyenlieu := gen_random_uuid();
        INSERT INTO "NhomSP" ("Id", "TenNhom", "MoTa", "PhanLoai", "NgayTao", "NgayCapNhat")
        VALUES (v_nhom_nguyenlieu, 'Nguyen lieu', 'Nhom nguyen lieu pha che', 4, v_now, v_now);
    END IF;

    -- Products
    SELECT "Id" INTO v_sp_cafeden FROM "Sanpham" WHERE "TenSP" = 'Ca phe den' LIMIT 1;
    IF v_sp_cafeden IS NULL THEN
        v_sp_cafeden := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_cafeden, v_nhom_cafe, 'Ca phe den', 'Ca phe den da', 30000, 12000, 120, 20, 'ly', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_bacxiu FROM "Sanpham" WHERE "TenSP" = 'Bac xiu' LIMIT 1;
    IF v_sp_bacxiu IS NULL THEN
        v_sp_bacxiu := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_bacxiu, v_nhom_cafe, 'Bac xiu', 'Bac xiu da', 35000, 15000, 100, 20, 'ly', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_trasua FROM "Sanpham" WHERE "TenSP" = 'Tra sua tran chau' LIMIT 1;
    IF v_sp_trasua IS NULL THEN
        v_sp_trasua := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_trasua, v_nhom_trasua, 'Tra sua tran chau', 'Tra sua truyen thong', 40000, 18000, 90, 15, 'ly', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_tiramisu FROM "Sanpham" WHERE "TenSP" = 'Tiramisu' LIMIT 1;
    IF v_sp_tiramisu IS NULL THEN
        v_sp_tiramisu := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_tiramisu, v_nhom_banh, 'Tiramisu', 'Banh tiramisu mieng', 45000, 22000, 50, 10, 'mieng', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_cafebot FROM "Sanpham" WHERE "TenSP" = 'Cafe bot' LIMIT 1;
    IF v_sp_cafebot IS NULL THEN
        v_sp_cafebot := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_cafebot, v_nhom_nguyenlieu, 'Cafe bot', 'Nguyen lieu pha cafe', 0, 350, 10000, 1000, 'g', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_suadac FROM "Sanpham" WHERE "TenSP" = 'Sua dac' LIMIT 1;
    IF v_sp_suadac IS NULL THEN
        v_sp_suadac := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_suadac, v_nhom_nguyenlieu, 'Sua dac', 'Nguyen lieu sua dac', 0, 200, 8000, 800, 'ml', true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_sp_cafesua FROM "Sanpham" WHERE "TenSP" = 'Cafe sua' LIMIT 1;
    IF v_sp_cafesua IS NULL THEN
        v_sp_cafesua := gen_random_uuid();
        INSERT INTO "Sanpham"
        ("Id", "IdNhom", "TenSP", "MoTa", "GiaBan", "GiaNhap", "SoLuongTon", "SLTonMin", "DonViTinh", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_sp_cafesua, v_nhom_cafe, 'Cafe sua', 'Cafe sua da', 38000, 16000, 9999, 0, 'ly', true, v_now, v_now);
    END IF;

    -- Customers, employees, invoice sample
    SELECT "Id" INTO v_khachle FROM "Khachhang" WHERE "TenKH" = 'Khach le' LIMIT 1;
    IF v_khachle IS NULL THEN
        v_khachle := gen_random_uuid();
        INSERT INTO "Khachhang"
        ("Id", "TenKH", "Sdt", "Email", "DiaChi", "CongNo", "IsActive", "NgayTao", "NgayCapNhat")
        VALUES (v_khachle, 'Khach le', NULL, NULL, NULL, 0, true, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_nhanvien FROM "Nhanvien" WHERE "TenNV" = 'Nhan vien mac dinh' LIMIT 1;
    IF v_nhanvien IS NULL THEN
        v_nhanvien := gen_random_uuid();
        INSERT INTO "Nhanvien"
        ("Id", "TenNV", "Sdt", "Email", "DiaChi", "CMND", "NgaySinh", "ChucVu", "Luong", "TrangThai", "NgayVaoLam", "NgayThaiPhuc", "NgayTao", "NgayCapNhat")
        VALUES (v_nhanvien, 'Nhan vien mac dinh', NULL, NULL, NULL, NULL, NULL, 'Thu ngan', 9000000, 1, v_now, NULL, v_now, v_now);
    END IF;

    SELECT "Id" INTO v_hoadon FROM "Hoadon" WHERE "MaHD" = 'HD-SEED-0001' LIMIT 1;
    IF v_hoadon IS NULL THEN
        v_hoadon := gen_random_uuid();
        INSERT INTO "Hoadon"
        ("Id", "MaHD", "IdKH", "IdNV", "NgayLapHD", "ThanhTien", "GiamGia", "TongCong", "PhuongThucThanhToan", "TrangThai", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES (v_hoadon, 'HD-SEED-0001', v_khachle, v_nhanvien, v_now, 30000, 0, 30000, 1, 2, 'Hoa don seed mau', v_now, v_now);
    END IF;

    SELECT "Id" INTO v_hoadonct FROM "HoadonCT" WHERE "IdHD" = v_hoadon AND "IdSP" = v_sp_cafeden LIMIT 1;
    IF v_hoadonct IS NULL THEN
        v_hoadonct := gen_random_uuid();
        INSERT INTO "HoadonCT"
        ("Id", "IdHD", "IdSP", "SoLuong", "DonGia", "ThanhTien", "GhiChu")
        VALUES (v_hoadonct, v_hoadon, v_sp_cafeden, 1, 30000, 30000, 'Dong seed mau');
    END IF;

    -- Optional sample records for the rest of the app.
    IF NOT EXISTS (SELECT 1 FROM "Phieunhap" WHERE "MaPN" = 'PN-SEED-0001') THEN
        INSERT INTO "Phieunhap"
        ("Id", "MaPN", "IdNCC", "IdNV", "NgayLapPN", "TongTien", "TrangThai", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES (gen_random_uuid(), 'PN-SEED-0001', gen_random_uuid(), v_nhanvien, v_now, 1500000, 0, 'Phieu nhap seed mau', v_now, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Phieuchi" WHERE "MaPC" = 'PC-SEED-0001') THEN
        INSERT INTO "Phieuchi"
        ("Id", "MaPC", "IdNV", "IdNCC", "NgayLapPC", "SoTien", "PhuongThucThanhToan", "LoaiChiPhi", "TrangThai", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES (gen_random_uuid(), 'PC-SEED-0001', v_nhanvien, NULL, v_now, 500000, 1, 0, 0, 'Phieu chi seed mau', v_now, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Dinhluong" WHERE "IdSP" = v_sp_cafesua AND "IdThanhPhan" = v_sp_cafebot) THEN
        INSERT INTO "Dinhluong"
        ("Id", "IdSP", "IdThanhPhan", "SoLuong", "DonVi", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES (gen_random_uuid(), v_sp_cafesua, v_sp_cafebot, 20, 'g', '1 ly cafe sua dung 20g cafe', v_now, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Dinhluong" WHERE "IdSP" = v_sp_cafesua AND "IdThanhPhan" = v_sp_suadac) THEN
        INSERT INTO "Dinhluong"
        ("Id", "IdSP", "IdThanhPhan", "SoLuong", "DonVi", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES (gen_random_uuid(), v_sp_cafesua, v_sp_suadac, 30, 'ml', '1 ly cafe sua dung 30ml sua', v_now, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Tieuhao" WHERE "IdHoadonCT" = v_hoadonct) THEN
        INSERT INTO "Tieuhao"
        ("Id", "IdSP", "IdHoadonCT", "SoLuong", "DonGiaVon", "NgayTao")
        VALUES (gen_random_uuid(), v_sp_cafeden, v_hoadonct, 1, 12000, v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Chamcong" WHERE "IdNV" = v_nhanvien AND "Ngay"::date = v_now::date) THEN
        INSERT INTO "Chamcong"
        ("Id", "IdNV", "Ngay", "GioVao", "GioRa", "TrangThai", "GhiChu", "NgayTao")
        VALUES (gen_random_uuid(), v_nhanvien, v_now, '08:00:00', '17:00:00', 0, 'Cham cong seed mau', v_now);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM "Bangluong" WHERE "IdNV" = v_nhanvien AND "Nam" = EXTRACT(YEAR FROM v_now)::int AND "Thang" = EXTRACT(MONTH FROM v_now)::int) THEN
        INSERT INTO "Bangluong"
        ("Id", "IdNV", "Nam", "Thang", "SoGio", "Luong", "PhuCap", "KhauTru", "TongLuong", "TrangThai", "GhiChu", "NgayTao", "NgayCapNhat")
        VALUES (gen_random_uuid(), v_nhanvien, EXTRACT(YEAR FROM v_now)::int, EXTRACT(MONTH FROM v_now)::int, 176, 9000000, 500000, 0, 9500000, 0, 'Bang luong seed mau', v_now, v_now);
    END IF;

    RAISE NOTICE 'Seed completed successfully.';
END $$;

COMMIT;
